apiVersion: v1
kind: Service
metadata:
  name: flask-service
spec:
  selector:
    app: flask-app
  ports:
    - protocol: TCP
      port: 80            # VMs port (service running on k8s cluster that port, not exectly a VMs port)
      targetPort: 5000    # containers port
  type: LoadBalancer