---
- name: Hello There
  hosts: all
  become: true
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install wget
      apt:
        name: wget
        state: present

    - name: Install tar
      apt:
        name: tar
        state: present

    - name: Download dotnet (make sure this is for the right architecture!)
      command: wget https://github.com/IBM/dotnet-s390x/releases/download/v10.0.100-preview.6.25302.104/dotnet-sdk-10.0.100-preview.6.25302.104-linux-ppc64le.tar.gz

    - name: Install nginx
      apt:
        name: nginx
        state: present

    - name: Start nginx
      service:
        name: nginx
        state: started

    - name: Get Nginx version
      command: nginx -v
      register: versionNginx
      ignore_errors: yes

    - name: Show Nginx version
      debug:
        msg: "Nginx version is: {{ versionNginx.stderr }}"